services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8008
    depends_on:
      - api